### ISSUE TITLE
[QoL feature improvement] Re-generate new keys/chat names button

### ISSUE THREAD

**Issue by SisyphusRising** [status-im/status-mobile#14485]
As a new user, when first generating new keys, I wondered why there was no refresh button for the randomly generated keys/chat names. 

As a new user, when first generating new keys, I want to have a "refresh" or "regenerate" button so that it is easier to cycle thru random chat names instead of pressing cancel and re-clicking generate keys button. I think this would offer a smoother new user UX with less friction if you don't like the chat names generated because of the character length, un-rememberability, aesthetically, or whatever the reason may be.

I realize this is low priority and a minor QoL improvement, but thought to suggest it nonetheless.

![IMG_20221203_082213](https://user-images.githubusercontent.com/108058775/205445672-256f2399-6325-4fe2-bec5-cb68c6e386da.jpg)

**Comment by du64** [comment]
The three word names and chat key selection are being removed in favor of letting the user pick a username (not ENS).

**Comment by cammellos** [comment]
Closing as this will not apply in the next release, thanks for the suggestion @SisyphusRising !
